In [20]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud,STOPWORDS
import numpy as np
%matplotlib inline
from sklearn.model_selection import train_test_split

In [35]:
import os

In [36]:
test_size = 0.3
random_seed = 42

In [48]:
df = pd.read_csv("data/raw/dataset.csv")

In [49]:
df

                                                    Text  language
0      klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1      sebes joseph pereira thomas  på eng the jesuit...   Swedish
2      ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3      விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4      de spons behoort tot het geslacht haliclona en...     Dutch
...                                                  ...       ...
21995  hors du terrain les années  et  sont des année...    French
21996  ใน พศ  หลักจากที่เสด็จประพาสแหลมมลายู ชวา อินเ...      Thai
21997  con motivo de la celebración del septuagésimoq...   Spanish
21998  年月，當時還只有歲的她在美國出道，以mai-k名義推出首張英文《baby i like》，由...   Chinese
21999   aprilie sonda spațială messenger a nasa și-a ...  Romanian

[22000 rows x 2 columns]

In [50]:
df = df.drop_duplicates(subset='Text')
df = df.reset_index(drop=True)

In [51]:
df.shape

(21859, 2)

In [52]:
#cleaning
from nltk.corpus import stopwords
import re
import unicodedata
from bs4 import BeautifulSoup

In [53]:
def clean_text(text):
    if "<" in text:
        text = BeautifulSoup(text, 'html.parser').get_text()
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

    text = re.sub(r'[^a-zA-Z0-9]', ' ', text)

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    text = re.sub(r'\s+', ' ', text).strip()

    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    text = ' '.join(filtered_words)

    return text

In [54]:
df["Text"] = df["Text"].apply(clean_text)

In [55]:
df.isna().sum()

Text        0
language    0
dtype: int64

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [57]:
train_df, test_df = train_test_split(
        df, test_size=test_size, random_state=random_seed, stratify=df["language"]
    )

In [58]:
train_df

                                                    Text   language
5897                                                          Hindi
19099                                                        Arabic
13352                                                          Urdu
18001  le chien dartois est un chien dordre de taille...     French
2803   aprovizionarea cu apa beneficiat de mai multe ...   Romanian
...                                                  ...        ...
6803   laeva algne pikkus oli laius ja suvis kogumahu...   Estonian
13736  adversaire du fascisme il rejoint le parti com...     French
14219  os escritos de peregrinos indicam que poco de ...  Portugese
21185                                                          Urdu
11316  de la saison la saison la premiere division se...     French

[15301 rows x 2 columns]

In [59]:
test_df.shape

(6558, 2)

In [60]:
len(df["Text"][1])

137

In [61]:
df.groupby("language").size()

language
Arabic         998
Chinese       1000
Dutch          996
English       1000
Estonian       999
French         990
Hindi          990
Indonesian     975
Japanese      1000
Korean        1000
Latin          953
Persian       1000
Portugese      997
Pushto         993
Romanian      1000
Russian        999
Spanish        996
Swedish        992
Tamil          981
Thai          1000
Turkish       1000
Urdu          1000
dtype: int64

In [62]:
df["language"].unique()

<StringArray>
[  'Estonian',    'Swedish',       'Thai',      'Tamil',      'Dutch',
   'Japanese',    'Turkish',      'Latin',       'Urdu', 'Indonesian',
  'Portugese',     'French',    'Chinese',     'Korean',      'Hindi',
    'Spanish',     'Pushto',    'Persian',   'Romanian',    'Russian',
    'English',     'Arabic']
Length: 22, dtype: str